spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://localhost:3306/srs
        username: srs
        password: srs123!!
        sql-script-encoding: UTF-8
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                jdbc:
                    batch_size: 200
                order_inserts: true
                order_updates: true

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
