spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://localhost:3306/srs
        username: srs
        password: srs123!!
        sql-script-encoding: UTF-8

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

logging:
    config: classpath:logback-local.xml
