version: '2.1'

services:
    eureka:
        build: ../../cloud/eureka
        mem_limit: 350m
        ports:
            - "8761:8761"

    gateway:
        build: ../../cloud/gateway
        mem_limit: 350m
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - SERVER_SSL_KEY_STORE=file:/keystore/gateway-docker-compose.p12
            - SERVER_SSL_KEY_STORE_PASSWORD=Touchme7!!
        volumes:
            - $PWD/keystore:/keystore
        ports:
            - "443:8080"

    common:
        build: ../../services/common
        mem_limit: 350m
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        depends_on:
            mariadb:
                condition: service_healthy

    mariadb:
        image: mariadb:10
        mem_limit: 350m
        ports:
            - "3306:3306"
        environment:
            - TZ=Asia/Seoul
            - MYSQL_HOST=localhost
            - MYSQL_PORT=3306
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=srs
            - MYSQL_USER=srs
            - MYSQL_PASSWORD=srs123!!
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-usrs", "-psrs123!!", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 10