spring:
    redis:
        host: redis
        port: 6379
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://mariadb:3306/srs
        username: srs
        password: srs123!!
        sql-script-encoding: UTF-8
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5
#    boot:
#        admin:
#            client:
#                auto-registration: false
#                url: http://localhost:8081/
#management:
#    endpoint:
#        health:
#            show-details: always
#    endpoints:
#        web:
#            exposure:
#                include: "*"

logging:
    config: classpath:logback-docker.xml