spring:
    redis:
        host: redis
        port: 6379
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://mariadb:3306/srs
        username: srs
        password: srs123!!
        sql-script-encoding: UTF-8
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    boot:
        admin:
            client:
                auto-registration: true
                url: http://admin:8000/
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"

eureka:
    client:
        service-url:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
        initial-instance-info-replication-interval-seconds: 5
        registry-fetch-interval-seconds: 5
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 5
