spring:
    redis:
        host: localhost
        port: 6379
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:srs
        username: srs
        password: srs123!!
        sql-script-encoding: UTF-8
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    batch_size: 200
                format_sql: true
                order_inserts: true
                order_updates: true

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

logging:
    level:
        org.hibernate.SQL: debug
