spring:
    redis:
        host: localhost
        port: 6379
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mariadb://localhost:3306/srs
        username: srs
        password: srs123!!
        sql-script-encoding: UTF-8
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true

logging:
    config: classpath:logback-test.xml