spring:
    data:
        redis:
            repositories:
                enabled: true
    profiles:
        active: local
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MariaDB103Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    batch_size: 200
                order_inserts: true
                order_updates: true
    output:
        ansi:
            enabled: always


# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# echo 'srs-backend-spring-boot-jwt-secret-key-for-restapi' | base64
jwt-security:
    secretKey: "srs-backend-jwt-secret-key-jeawoo.jeong@gmail.com"
    accessTokenExpiration: "900000" # 15 minute
    refreshTokenExpiration: "3600000000" # 1000L * 60 * 60 * 24
    accessTokenHeader: "X-AUTH-ATOKEN"
    refreshTokenHeader: "X-AUTH-RTOKEN"