server:
    ssl:
        key-store-type: PKCS12
        key-store: classpath:keystore/gateway-local.p12
        key-store-password: Touchme7!!
        key-alias: localhost
management:
    endpoint:
        gateway:
            enabled: true # default: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        initialInstanceInfoReplicationIntervalSeconds: 5
        registryFetchIntervalSeconds: 5
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5