server:
    port: 8080

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                - id: common-service
                  uri: lb://common-service
                  predicates:
                    - Path=/common/**
                - id: openapi
                  uri: http://localhost:${server.port}
                  predicates:
                    - Path=/v3/api-docs/**
                  filters:
                    - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

    output:
        ansi:
            enabled: always

management:
    endpoints:
        web:
            exposure:
                include: gateway

logging:
    level:
        root: INFO
        com.jaewoo.srs.cloud: DEBUG