server:
    port: 8080
    ssl:
        key-store-type: PKCS12
        key-store: classpath:keystore/gateway-local.p12
        key-store-password: Touchme7!!
        key-alias: localhost

spring:
    application:
        name: gateway
    cloud:
        gateway:
            routes:
                - id: common-service
                  uri: lb://common-service
                  predicates:
                    - Path=/common/**
                  filters:
                    - RewritePath=/common/(?<path>.*), /$\{path}
                - id: openapi
                  uri: http://localhost:${server.port}
                  predicates:
                    - Path=/v3/api-docs/**
                  filters:
                    - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

    output:
        ansi:
            enabled: always

management.endpoints.web.exposure.include: "*"

logging:
    level:
        root: INFO
        com.jaewoo.srs.cloud: DEBUG